### ISSUE TITLE
FYI: universe

### ISSUE THREAD

**Issue by phadej** [AshleyYakeley/countable#1]
There is http://hackage.haskell.org/package/universe  and http://hackage.haskell.org/package/enumerable. How this package is different (I.e. better), taken into account https://github.com/dmwit/universe/issues/23 and other further development opportunities

**Comment by AshleyYakeley** [comment]
AFAICT, those packages deal with `Countable` and `Finite` classes, but not `Searchable`.

For example, because we have `Searchable (Integer -> Bool)`, even though we don't have `Finite (Integer -> Bool)`, we can provide `forevery :: ((Integer -> Bool) -> Bool) -> Bool` as well as an extensional `Eq ((Integer -> Bool) -> Integer)`.
